remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
title: Data Science and Computing Versity 
description: The journey to becoming a proficient computer scientist and data scientist.
