remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
title: Data Science and Computing Versity 
description: A world of possibilities in the realm of Computing and data Science.